### ISSUE TITLE
Add slogan collaboration 1st code 2nd to profile readme

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/.github#1]

**Comment by FayasNoushad** [comment]
Yeah, Its important for community. 👍

**Comment by ShlokMohanty** [comment]
@schmelto so what should be exactly done for closing this issue?
is it like we should add the profile of the contributors or its about something else?

**Comment by FayasNoushad** [comment]
> @schmelto so what should be exactly done for closing this issue?
> is it like we should add the profile of the contributors or its about something else?

Its just a profile README of @EddieHubCommunity

**Comment by schmelto** [comment]
> > @schmelto so what should be exactly done for closing this issue?
> > is it like we should add the profile of the contributors or its about something else?
> 
> Its just a profile README of @EddieHubCommunity

Yes
