### ISSUE TITLE
Social Links need Emphasis

### ISSUE THREAD

**Issue by Akshu-on-github** [EddieHubCommunity/.github#12]
## Description

The links to our community's activity sites are rather lost in the text - I'd suggest using Icons (like the one in my profile) or badges (shield.io or the like) to draw attention to these. If centred, it would also help reduce asymmetric whitespace

<img src ="https://user-images.githubusercontent.com/61582763/138277502-8e3e4fa8-ee09-4bb8-812f-20ef9b665ca2.png" width=50%><img src = "https://user-images.githubusercontent.com/61582763/138277185-51c97cc2-c601-4fa4-a100-1e825444d8c2.png" width=49%>

**Comment by krishguptadev** [comment]
Can I work on this?

**Comment by Akshu-on-github** [comment]
Go for it @krishdevdb!
