### ISSUE TITLE
Add basic issue forms (feature request, bug, etc.) to be used in all the other repositories

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/.github#18]

**Comment by Saurabhpatil-dev** [comment]
@Panquesito7 What needs to be done? Can you explain please. 

I can take it up, if I can make the changes.

**Comment by Panquesito7** [comment]
You can add issue templates similar to these ones https://github.com/web3community/web3community.github.io/tree/main/.github/ISSUE_TEMPLATE 🙂

**Comment by Saurabhpatil-dev** [comment]
@Panquesito7 Can you check the pull request number #27 /
I already created a PR for it today.

**Comment by KendallDoesCoding** [comment]
> @Panquesito7 Can you check the pull request number #27 I already created a PR for it today. Let me know if this is different issue.

This doesn't seem to be added with #27

**Comment by nhcarrigan** [comment]
Closed in the above mentioned PR.

**Comment by KendallDoesCoding** [comment]
> Closed in the above mentioned PR.

No.

> This doesn't seem to be added with https://github.com/EddieHubCommunity/.github/pull/27

**Comment by nhcarrigan** [comment]
How is it not resolved? This issue asks for issue forms to be added, that PR adds issue forms.

**Comment by KendallDoesCoding** [comment]
Ik the issue
