### ISSUE TITLE
Hide unused features

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/.github#4]
Suggestion to hide:
- Hide Wiki tab
- Hide Releases and Packages

**Comment by schmelto** [comment]
@eddiejaoude I think you are the only one who can make this :)

**Comment by vinzvinci** [comment]
Up

**Comment by krishguptadev** [comment]
Nice catch, also we might want to disable actions and projects...

**Comment by eddiejaoude** [comment]
Thanks @vinzvinci 👍 Done
