### ISSUE TITLE
[OTHER] Banned from discord

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/.github#43]
### What would you like to share?

Hi,

I was banned from the discord? Why

**Comment by eddiejaoude** [comment]
Unfortunately, you were banned because kept breaking rule number 1, please see screenshot attached

<img width="724" alt="Screenshot 2022-02-24 at 19 42 26" src="https://user-images.githubusercontent.com/624760/155517834-aad61bbf-aaa9-4cd0-b644-1e4d9ee1db90.png">

**Comment by KendallDoesCoding** [comment]
> Unfortunately, you were banned from Discord because kept breaking rule number 1 😢 , please see screenshot attached.
> 
> We appreciate your open source collaboration on GitHub, if there is anything we can do to help, please let us know 🤓
> 
> <img alt="Screenshot 2022-02-24 at 19 42 26" width="724" src="https://user-images.githubusercontent.com/624760/155517834-aad61bbf-aaa9-4cd0-b644-1e4d9ee1db90.png">

Yeah, I'm really sorry about that and understand the decision.

I basically had a plan to start a open source organization and wanted to ask for feedback from the server and ideas, if possible.

**Comment by eddiejaoude** [comment]
Hi Kendall, after some discussion we have decided to remove the Discord ban. However please read and consider the rules before rejoining

We look forward to collaborating with you again publicly not in DMs - as we say in EddieHub collaboration 1st Code 2nd.

**Comment by KendallDoesCoding** [comment]
> Hi Kendall, after some discussion we have decided to remove the Discord ban. However please read and consider the rules before rejoining
> 
> We look forward to collaborating with you again publicly not in DMs - as we say in EddieHub collaboration 1st Code 2nd.

Hi Eddie, Thanks for the decision made by yall. I really appreciate it.

Yes, I will ensure not to dm anyone relating to help of my projects, without their permission to dm them.
