### ISSUE TITLE
[FEATURE] Badge to tell how many repos the organization has

### ISSUE THREAD

**Issue by KendallDoesCoding** [EddieHubCommunity/.github#44]
### Description

A badge to tell how many repos the organization has should be added to README.md

**Comment by schmelto** [comment]
I love badges but I think a badge telling the number or repos is not needed cause I'm not a fan of duplicate information on a page. But as always this is only my personal opinion :)

![image](https://user-images.githubusercontent.com/30869493/155672504-03067c55-b325-4987-83e8-0da83b683d68.png)

**Comment by KendallDoesCoding** [comment]
> I love badges but I think a badge telling the number or repos is not needed cause I'm not a fan of duplicate information on a page. But as always this is only my personal opinion :)
> 
> ![image](https://user-images.githubusercontent.com/30869493/155672504-03067c55-b325-4987-83e8-0da83b683d68.png)

True.. I forgot the repos button existed there LOL
