### ISSUE TITLE
[BUG] Update GitHub Help link to GitHub Docs

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/.github#46]
### Description

The README file (not the readme profile, but the readme of this repository itself) has a link to a GitHub Docs article but is using the old GitHub Help link. It will redirect you automatically, but it's good to keep us updated. :)

### Screenshots

![image](https://user-images.githubusercontent.com/51391473/169589599-f0eec400-6655-458c-94e1-30b206d2155b.png)

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by Shekhar-Dangi** [comment]
@Panquesito7  I want to update this link. 
Please let me know if I can.

**Comment by eddiejaoude** [comment]
Sorry @Shekhar-Dangi a PR already came in. Next time feel free to raise a PR

**Comment by Shekhar-Dangi** [comment]
@eddiejaoude  No problem :)
