### ISSUE TITLE
[DOCS] The .github-private README is being displayed, not this repo profile readme.

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/.github#51]
### Description

I am not sure if it was intended, but the EddieHub profile README is looking like this:
![image](https://user-images.githubusercontent.com/70807500/171960480-d82b7f8d-d1ab-4bc7-bfb5-95402213884f.png) 
This has come from this repo [https://github.com/EddieHubCommunity/.github-private/blob/main/profile/README.md](https://github.com/EddieHubCommunity/.github-private/blob/main/profile/README.md)

However, here on this repo, it is looking like this, how it used to:
![image](https://user-images.githubusercontent.com/70807500/171960625-8836daf5-aecb-4577-9aa6-43d3fa36e3e6.png)

Is this the new README? I have not been active on EddieHub recently, and when I came back, I saw how the README changed, yet it was the same still here. 
Thank you.

**Comment by Panquesito7** [comment]
Hey there! The `.github-private` repository is how will the organization profile will look for members. The `.github` repository is global for all users not inside the organization.

If you're a member, you can check how it looks both for normal and member users. 🙂

![image](https://user-images.githubusercontent.com/51391473/171972665-47115f7d-caaf-4cce-9faf-86a2a41fb76b.png)

**Comment by eddiejaoude** [comment]
Thanks @Panquesito7 👍 

We now show different customised Org READMEs for members and non-members

**Comment by CodingSpecies** [comment]
@eddiejaoude @Panquesito7 Thank you for the answer! I understand now. Thank you.
