### ISSUE TITLE
Bullet list question on public README.

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/.github#55]
#### The list on the public README seems confusing as it is both an ordered list and an unordered list:

![image](https://user-images.githubusercontent.com/70807500/184442571-58613288-7791-4521-8bec-0336222d563c.png)
There is bullet points and numbers next to eachother and I was wondering if we could keep one type.
Thank you.

**Comment by jasham** [comment]
@CodingSpecies Please assign this issue to me so that I can fix.

**Comment by CodingSpecies** [comment]
@jasham I am not able to assign you to this, as I am not a maintainer, but feel free to work on it and open a pull request!

**Comment by jasham** [comment]
Thanks @schmelto & @CodingSpecies
