### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Johnmiicheal** [EddieHubCommunity/.github#57]
### What would you like to share?

I have not yet been invited to the organisation...I want to be a part of this organisation so I can grow with the opensource community

**Comment by schmelto** [comment]
Please use following link to get an invite to the github org
https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization
