### ISSUE TITLE
GitHub Actions Enhancements

### ISSUE THREAD

**Issue by ShaikMoAbdullah** [EddieHubCommunity/.github#58]
### What would you like to share?

To add Kubescape YAML actions file to the project

**Comment by eddiejaoude** [comment]
Thank you for raising but there is no `kubernetes` directory is this project for deployment, so it does not make sense to add the GitHub Action here to check it - please only add it to projects that have the `kubernetes` config

**Comment by ShaikMoAbdullah** [comment]
I will keep that in mind Eddie.
