### ISSUE TITLE
Some more briefing in READme will be helpful

### ISSUE THREAD

**Issue by abrahamalen** [EddieHubCommunity/.github#6]
Elaborate the READme

**Comment by CodingSpecies** [comment]
@abrahamalen please can you explain further on how you would exactly like us to elaborate on the readme thank you

**Comment by CodingSpecies** [comment]
So far we have created pull requests to add more info about the org to the readme but if there is anything else feel free to share.

**Comment by abrahamalen** [comment]
@CodingSpecies 
- It could be nice if we add the eddyhub.org link in the readme even though it is below that title, providing it in READme increases visibility.
- Could provide a brief description of the objective
- Can pinpoint the repo's consisting of specific things.

**Comment by CodingSpecies** [comment]
Thank you for expanding and sharing your ideas @abrahamalen

**Comment by abrahamalen** [comment]
My open-source journey began from the eddyhub youtube videos, So I love this organization.

**Comment by CodingSpecies** [comment]
Thank you for contributing!

**Comment by abrahamalen** [comment]
Hoping to contribute more

**Comment by krishguptadev** [comment]
Can I get assigned to this issue?

**Comment by krishguptadev** [comment]
btw which readme is to be elaborated? the project readme or the profile one?

**Comment by krishguptadev** [comment]
umm @schmelto could you tell?

**Comment by schmelto** [comment]
I think we could elaborate the repo readme a little bit more
