### ISSUE TITLE
Enhance GitHub Automatic Issue and Pull request Bot

### ISSUE THREAD

**Issue by NS007-dev** [EddieHubCommunity/.github#61]
### What would you like to share?

When a new contributor opens an issue or pull request, the github action bot responds with a message saying:
![image](https://user-images.githubusercontent.com/70807500/192634189-b51dcda8-2f43-4cfa-b46d-9766986f27b7.png)

I think, the text should be formatted and enhanced to something like this:

-----------------

### Welcome @___!
Thank you so much for your first pull request! ✨
Welcome to our community! 🎉
Also join us in the EddieHub Discord for realtime chat and calls at [👉 http://discord.eddiehub.org 👈](http://discord.eddiehub.org) 

------------------

Thank you.

**Comment by ATREAY** [comment]
Hi @NS007-dev, is this issue still active, or has it been resolved?

**Comment by ATREAY** [comment]
Hi @NS007-dev, is this issue still open??

**Comment by NS007-dev** [comment]
Hi @ATREAY 
I am sorry for the delayed reply. I haven't been active on Github unfortunately and I am not sure if this issue has been resolved. Thanks.

**Comment by eddiejaoude** [comment]
thank you for raising the issue, I don't think this repo has this functionality, so I will close
