### ISSUE TITLE
[OTHER]Help!

### ISSUE THREAD

**Issue by padrone1225** [EddieHubCommunity/.github#65]
### What would you like to share?

Help!

### Additional information

Hi, this is Tenshi Ota. I am a member of the EddieHub community. I recently joined this community. But I couldn't join the community's Discord. This is because you can't log in to discord.com. So can you invite me to the discord? Help.

**Comment by eddiejaoude** [comment]
If you are having trouble with your Discord account, please contact Discord support directly, we cannot help with that
