### ISSUE TITLE
Fix: description for issue template to be more generalized. 

### ISSUE THREAD

**Issue by kumarsonsoff3** [EddieHubCommunity/.github#66]
### What would you like to share?

Issue templates for this repo should be more generalized as, these ones are used as default issue template for all other projects in the org. 

- **For the General Feature Request template, the description should be modified to something like:**
`Suggest features, propose improvements, discuss new ideas!`

![image](https://user-images.githubusercontent.com/88786642/197389419-5e7e0bba-4428-495e-a03f-bf61815786ce.png)

### Additional information

Modifications should be made in this [`feature_request.yml`](https://github.com/EddieHubCommunity/.github/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml) file.

**Comment by Panquesito7** [comment]
Nice catch; thank you! Would you like to work on this?

**Comment by kumarsonsoff3** [comment]
For sure, would love to work on this!
