### ISSUE TITLE
[DOCS] Inconsistent list numbering

### ISSUE THREAD

**Issue by AldrinSeanPereira** [EddieHubCommunity/.github#70]
### Description

The list of links and points to use Eddiehub has inconsistent numbering

It has dots as well as numbers. I suggest using 1 style for consistency

### Screenshots

<img width="685" alt="Screenshot (215)" src="https://user-images.githubusercontent.com/54813708/206421467-cbad2f3a-6b25-4cf9-ab7d-69974e104b18.png">

**Comment by eddiejaoude** [comment]
Thanks Sean 👍
