### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by nithin999989** [EddieHubCommunity/.github#77]
### Description

Only discord and youtube links are available I propose to add Twitter and Linkedin Hyperlinks also

### Screenshots

![opensource](https://user-images.githubusercontent.com/82808965/232409373-8bc3e46b-2fb7-440d-bb84-4927981a1209.png)

**Comment by nithin999989** [comment]
@eddiejaoude please assign this to me as this will be my first contribution

**Comment by eddiejaoude** [comment]
There is no twitter for EddieHub so I will close this issue
