### ISSUE TITLE
Bug : Horizontal Line in Ambassador Program while making site responsive

### ISSUE THREAD

**Issue by Kuroo7** [EddieHubCommunity/.github#78]
### Description

There is a bug in Ambassador Program page( https://www.eddiehub.org/ambassador-program ) on making this  page responsive.
There is a line between terms and guide line 4 and 3 and also above Vyom Jain.

### Screenshots

![Screenshot (98)](https://github.com/EddieHubCommunity/.github/assets/107842948/dc822c3d-c4c8-4537-ab51-4cda30bf98b1)
![Screenshot (97)](https://github.com/EddieHubCommunity/.github/assets/107842948/8408e8b2-216a-4087-a136-04569e26333c)

**Comment by eddiejaoude** [comment]
Unfortunately this website is created with a no-code platform, so we can't make any changes, so I will close this issue
