### ISSUE TITLE
Add GIF of EddieHub

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/.github#8]
Is there some way we could add this in:

![](https://raw.githubusercontent.com/EddieHubCommunity/Branding/main/community/hubber-eddiehub.gif)

thank you

**Comment by schmelto** [comment]
Is it possible to make the gif more like a banner? I think that would be look nicer

**Comment by CodingSpecies** [comment]
I found this gif in the EddieHub branding repo. @schmelto

**Comment by schmelto** [comment]
Yeah think we could add this :)

**Comment by CodingSpecies** [comment]
Ok, please can you assign this to me @schmelto . thank you

**Comment by CodingSpecies** [comment]
#11 
I changed the gif and altered it to this: 
![hubber-eddiehub](https://user-images.githubusercontent.com/70807500/136846295-e58210b0-6ef1-4abc-ac39-ad076e0f00bb.gif)
