### ISSUE TITLE
[DOCS] wrong links in API section

### ISSUE THREAD

**Issue by j-grosse** [EddieHubCommunity/.github#81]
### Description

the two links in the API section of the docs should use eddiehub.io instead of the not working eddiehub.org

### Screenshots

![IMG_0719](https://github.com/EddieHubCommunity/.github/assets/103175813/46fd8538-2f1c-4d78-aa3c-fb3583a4d5e1)
![IMG_0720](https://github.com/EddieHubCommunity/.github/assets/103175813/4ad6d4ac-873a-440d-9634-3439ed6a371e)

### Additional information

I could change them and make a PR.

**Comment by j-grosse** [comment]
closed the issue  because it was created in the wrong repo. re-created it in „repo rater“

**Comment by eddiejaoude** [comment]
ok thanks for closing 👍
